### ISSUE TITLE
Abort on resize

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#23]
Here's the log:

```log

2020-10-20T15:40:33.669+0300	INFO	Changing pty size for pane 21: &{7 12 0 0}
2020-10-20T15:40:33.669+0300	INFO	Sending output to 1 dcs
free(): corrupted unsorted chunks
SIGABRT: abort
PC=0x7f76e1d6af47 m=18 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f76e1d6af47
stack: frame={sp:0x7f7681ffa9b0, fp:0x0} stack=[0x7f76817fb288,0x7f7681ffae88)
00007f7681ffa8b0:  0000000000000000  0000000000000000 
...
00007f7681ffaaa0:  ffffffffffffffff  ffffffffffffffff 

goroutine 83642 [syscall]:
runtime.cgocall(0x928df0, 0xc005799b20, 0xc0061ca680)
	/home/daonb/go/src/runtime/cgocall.go:133 +0x5b fp=0xc005799af0 sp=0xc005799ab8 pc=0x405b8b
main._Cfunc_tresize(0x7f76900061f0, 0x70000000c)
	_cgo_gotypes.go:192 +0x45 fp=0xc005799b20 sp=0xc005799af0 pc=0x9262c5
main.STResize.func1(0x7f76900061f0, 0x7000c)
	/home/daonb/src/webexec/st.go:25 +0x5f fp=0xc005799b50 sp=0xc005799b20 pc=0x92822f
main.STResize(0x7f76900061f0, 0xc00007000c)
	/home/daonb/src/webexec/st.go:25 +0x3f fp=0xc005799b70 sp=0xc005799b50 pc=0x927bbf
main.(*Pane).Resize(0xc005799e98, 0xc0061ca680)
	/home/daonb/src/webexec/pane.go:167 +0x15c fp=0xc005799bf8 sp=0xc005799b70 pc=0x92785c
main.(*Peer).OnCTRLMsg(0xc0052af730, 0xff01, 0xc005a22000, 0x5c, 0xffff)
	/home/daonb/src/webexec/peer.go:289 +0x9c4 fp=0xc005799f00 sp=0xc005799bf8 pc=0x922fb4
main.(*Peer).OnCTRLMsg-fm(0x44ca01, 0xc005a22000, 0x5c, 0xffff)
	/home/daonb/src/webexec/peer.go:261 +0x51 fp=0xc005799f38 sp=0xc005799f00 pc=0x9289c1
github.com/pion/webrtc/v2.(*DataChannel).onMessage(0xc00406a1e0, 0xc005a22001, 0xc005a22000, 0x5c, 0xffff)
	/home/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:279 +0x7e fp=0xc005799f70 sp=0xc005799f38 pc=0x85da2e
github.com/pion/webrtc/v2.(*DataChannel).readLoop(0xc00406a1e0)
	/home/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:329 +0x4d fp=0xc005799fd8 sp=0xc005799f70 pc=0x85ddad
runtime.goexit()
	/home/daonb/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc005799fe0 sp=0xc005799fd8 pc=0x465a41
created by github.com/pion/webrtc/v2.(*DataChannel).handleOpen
	/home/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:294 +0xfd
```

**Comment by tebeka** [comment]
What's `st.go`? Are we back on `master` branch?

**Comment by daonb** [comment]
Yep, back on master. I suspect the problem is the C code I copied from simple terminal.   The [resize](https://github.com/tuzig/webexec/blob/master/st.c#L1950) function looks dubious and I would start by writing some tests for it.

**Comment by daonb** [comment]
Another resize crash, this time with a different error

```
2020-11-02T12:43:52.590+0200	INFO	Changing pty size for pane 1: &{69 42 0 0}
2020-11-02T12:43:52.590+0200	INFO	Sending output to 2 dcs
SIGABRT: abort
PC=0x7fff6f7ff33a m=7 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff6f7ff33a
stack: frame={sp:0x70000a421c68, fp:0x0} stack=[0x70000a3a2350,0x70000a421f50)
000070000a421b68:  00007fff6f8927da  0000000000000000 
000070000a421b78:  000070000a421bc8  000070000a421bc0 
000070000a421b88:  0000000004dff000  000070000a422000 
000070000a421b98:  00007ffeefbff8a4  00007fff6f892765 
000070000a421ba8:  0000000000000050  000070000a421c90 
000070000a421bb8:  00007fff6f8aef24  0000003000000018 
000070000a421bc8:  000070000a421ca0  000070000a421be0 
000070000a421bd8:  0000000000000050  000070000a421c50 
000070000a421be8:  00007fff6f8af073  00007fff6f892765 
000070000a421bf8:  0000000004dff04d  0000000000000000 
000070000a421c08:  0000000000000000  000070000a421df8 
000070000a421c18:  000070000a421c88  0000000004dfe028 
000070000a421c28:  0000000000000050  000070000a421c58 
000070000a421c38:  0000000000000050  000070000a421c70 
000070000a421c48:  00007fff6f7fa91f  000070000a421cc0 
000070000a421c58:  0000000004dff000  0000000004dfe000 
000070000a421c68: <00007fff6f8bbe60  0000000000000003 
000070000a421c78:  0000000004dfe028  000070000a421cb0 
000070000a421c88:  0000000000000000  000070000a421cd0 
000070000a421c98:  00007fff6f786808  0000000004dfe028 
000070000a421ca8:  00007fff6f7fa399  00007ffffffff9df 
000070000a421cb8:  ffffffff04dfe000  0000000004dfe000 
000070000a421cc8:  0000000000000000  000070000a421d30 
000070000a421cd8:  00007fff6f87c50b  0000000004df2e00 
000070000a421ce8:  000070000a422000  000070000a421df0 
000070000a421cf8:  0000000000000000  00007fff6f89054d 
000070000a421d08:  0000000000000000  000000000000002a 
000070000a421d18:  0000000000000001  00000000000002a0 
000070000a421d28:  000000002d844800  000070000a421e10 
000070000a421d38:  00007fff6f87f40f  0000000300000000 
000070000a421d48:  0000000000000600  000000002d844800 
000070000a421d58:  0000000004def5b8  000000002d800000 
runtime: unknown pc 0x7fff6f7ff33a
stack: frame={sp:0x70000a421c68, fp:0x0} stack=[0x70000a3a2350,0x70000a421f50)
000070000a421b68:  00007fff6f8927da  0000000000000000 
000070000a421b78:  000070000a421bc8  000070000a421bc0 
000070000a421b88:  0000000004dff000  000070000a422000 
000070000a421b98:  00007ffeefbff8a4  00007fff6f892765 
000070000a421ba8:  0000000000000050  000070000a421c90 
000070000a421bb8:  00007fff6f8aef24  0000003000000018 
000070000a421bc8:  000070000a421ca0  000070000a421be0 
000070000a421bd8:  0000000000000050  000070000a421c50 
000070000a421be8:  00007fff6f8af073  00007fff6f892765 
000070000a421bf8:  0000000004dff04d  0000000000000000 
000070000a421c08:  0000000000000000  000070000a421df8 
000070000a421c18:  000070000a421c88  0000000004dfe028 
000070000a421c28:  0000000000000050  000070000a421c58 
000070000a421c38:  0000000000000050  000070000a421c70 
000070000a421c48:  00007fff6f7fa91f  000070000a421cc0 
000070000a421c58:  0000000004dff000  0000000004dfe000 
000070000a421c68: <00007fff6f8bbe60  0000000000000003 
000070000a421c78:  0000000004dfe028  000070000a421cb0 
000070000a421c88:  0000000000000000  000070000a421cd0 
000070000a421c98:  00007fff6f786808  0000000004dfe028 
000070000a421ca8:  00007fff6f7fa399  00007ffffffff9df 
000070000a421cb8:  ffffffff04dfe000  0000000004dfe000 
000070000a421cc8:  0000000000000000  000070000a421d30 
000070000a421cd8:  00007fff6f87c50b  0000000004df2e00 
000070000a421ce8:  000070000a422000  000070000a421df0 
000070000a421cf8:  0000000000000000  00007fff6f89054d 
000070000a421d08:  0000000000000000  000000000000002a 
000070000a421d18:  0000000000000001  00000000000002a0 
000070000a421d28:  000000002d844800  000070000a421e10 
000070000a421d38:  00007fff6f87f40f  0000000300000000 
000070000a421d48:  0000000000000600  000000002d844800 
000070000a421d58:  0000000004def5b8  000000002d800000 

goroutine 278 [syscall]:
runtime.cgocall(0x4528130, 0xc0000dfb20, 0xc0002ee8e0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0000dfaf0 sp=0xc0000dfab8 pc=0x400594b
main._Cfunc_tresize(0x56045f0, 0x450000002a)
	_cgo_gotypes.go:190 +0x45 fp=0xc0000dfb20 sp=0xc0000dfaf0 pc=0x45254c5
main.STResize.func1(0x56045f0, 0x45002a)
	/Users/daonb/src/webexec/st.go:25 +0x5f fp=0xc0000dfb50 sp=0xc0000dfb20 pc=0x452753f
main.STResize(0x56045f0, 0xc00045002a)
	/Users/daonb/src/webexec/st.go:25 +0x3f fp=0xc0000dfb70 sp=0xc0000dfb50 pc=0x4526ecf
main.(*Pane).Resize(0xc0000dfe98, 0xc0002ee8e0)
	/Users/daonb/src/webexec/pane.go:170 +0x15c fp=0xc0000dfbf8 sp=0xc0000dfb70 pc=0x4526aec
main.(*Peer).OnCTRLMsg(0xc00016a1c0, 0xff01, 0xc000478000, 0x5b, 0xffff)
	/Users/daonb/src/webexec/peer.go:289 +0x9c4 fp=0xc0000dff00 sp=0xc0000dfbf8 pc=0x45221b4
main.(*Peer).OnCTRLMsg-fm(0x404c101, 0xc000478000, 0x5b, 0xffff)
	/Users/daonb/src/webexec/peer.go:261 +0x51 fp=0xc0000dff38 sp=0xc0000dff00 pc=0x4527cd1
github.com/pion/webrtc/v2.(*DataChannel).onMessage(0xc0004e00f0, 0xc000478001, 0xc000478000, 0x5b, 0xffff)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:279 +0x7e fp=0xc0000dff70 sp=0xc0000dff38 pc=0x445cc1e
github.com/pion/webrtc/v2.(*DataChannel).readLoop(0xc0004e00f0)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:329 +0x4d fp=0xc0000dffd8 sp=0xc0000dff70 pc=0x445cf9d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000dffe0 sp=0xc0000dffd8 pc=0x4064ef1
created by github.com/pion/webrtc/v2.(*DataChannel).handleOpen
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:294 +0xfd
```

**Comment by daonb** [comment]
and again:

```
2020-11-10T10:19:14.557+0200	INFO	Got a CTRLMessage: "{\"type\":\"resize\",\"args\":{\"pane_id\":7,\"sx\":110,\"sy\":82},\"message_id\":12,\"time\":1604996354439}"

2020-11-10T10:19:14.558+0200	INFO	Changing pty size for pane 7: &{82 110 0 0}
2020-11-10T10:19:14.558+0200	INFO	Sending output to 1 dcs
SIGABRT: abort
PC=0x7fff727f133a m=13 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff727f133a
stack: frame={sp:0x70000a736c18, fp:0x0} stack=[0x70000a6b7350,0x70000a736f50)
000070000a736b18:  00007fff728847da  0000000000000000 
...
000070000a736d08:  000000000c89fc00  0000000000000020 

goroutine 4097 [syscall]:
runtime.cgocall(0x4527c10, 0xc000271b18, 0xc00036bf08)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000271ae8 sp=0xc000271ab0 pc=0x4004edb
main._Cfunc_tresize(0xc704990, 0x520000006e)
	_cgo_gotypes.go:190 +0x45 fp=0xc000271b18 sp=0xc000271ae8 pc=0x4524e55
main.STResize.func1(0xc704990, 0x52006e)
	/Users/daonb/src/webexec/st.go:25 +0x5f fp=0xc000271b48 sp=0xc000271b18 pc=0x452701f
main.STResize(0xc704990, 0xc00052006e)
	/Users/daonb/src/webexec/st.go:25 +0x3f fp=0xc000271b68 sp=0xc000271b48 pc=0x452692f
main.(*Pane).Resize(0xc000271e90, 0xc00036bf08)
	/Users/daonb/src/webexec/pane.go:178 +0x15c fp=0xc000271bf0 sp=0xc000271b68 pc=0x452654c
main.(*Peer).OnCTRLMsg(0xc00016a070, 0xff01, 0xc0005cc000, 0x5c, 0xffff)
	/Users/daonb/src/webexec/peer.go:299 +0x9bb fp=0xc000271f00 sp=0xc000271bf0 pc=0x452187b
main.(*Peer).OnCTRLMsg-fm(0x404b601, 0xc0005cc000, 0x5c, 0xffff)
	/Users/daonb/src/webexec/peer.go:271 +0x51 fp=0xc000271f38 sp=0xc000271f00 pc=0x45277b1
github.com/pion/webrtc/v2.(*DataChannel).onMessage(0xc0002784b0, 0xc0005cc001, 0xc0005cc000, 0x5c, 0xffff)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:279 +0x7e fp=0xc000271f70 sp=0xc000271f38 pc=0x445c1ae
github.com/pion/webrtc/v2.(*DataChannel).readLoop(0xc0002784b0)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:329 +0x4d fp=0xc000271fd8 sp=0xc000271f70 pc=0x445c52d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000271fe0 sp=0xc000271fd8 pc=0x4064481
created by github.com/pion/webrtc/v2.(*DataChannel).handleOpen
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:294 +0xfd
```

**Comment by daonb** [comment]
It could be a reentrancy thing. I'm going to add a mutex to protect the resize and we'll see how it goes.

**Comment by daonb** [comment]
```
2020-11-20T00:19:54.621+0200	INFO	Got a CTRLMessage: "{\"type\":\"resize\",\"args\":{\"pane_id\":1,\"sx\":35,\"sy\":54},\"message_id\":19,\"time\":1605824394519}"

2020-11-20T00:19:54.621+0200	INFO	Sending ctrl message: {"time":1605824394621,"message_id":19,"type":"ack","args":{"ref":19,"body":null}}
2020-11-20T00:19:54.621+0200	INFO	Got a CTRLMessage: "{\"type\":\"resize\",\"args\":{\"pane_id\":2,\"sx\":34,\"sy\":58},\"message_id\":20,\"time\":1605824394525}"

2020-11-20T00:19:54.621+0200	INFO	Changing pty size for pane 2: &{58 34 0 0}
2020-11-20T00:19:54.622+0200	INFO	Sending output to 1 dcs
2020-11-20T00:19:54.622+0200	INFO	Sending output to 1 dcs
2020-11-20T00:19:54.622+0200	INFO	Sending output to 1 dcs
fatal error: 2020-11-20T00:19:54.625+0200	INFO	Sending output to 1 dcs
2020-11-20T00:19:54.625+0200	INFO	Sending output to 1 dcs
unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x7fff72862bd3]

runtime stack:
runtime.throw(0x467b294, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 24068 [syscall]:
runtime.cgocall(0x4529670, 0xc00012db70, 0xc0000a2a50)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00012db40 sp=0xc00012db08 pc=0x400592b
main._Cfunc_tresize(0xc7040a0, 0x3a00000022)
	_cgo_gotypes.go:190 +0x45 fp=0xc00012db70 sp=0xc00012db40 pc=0x45266a5
main.STResize.func1(0xc7040a0, 0x3a0022)
	/Users/daonb/src/webexec/st.go:25 +0x5f fp=0xc00012dba0 sp=0xc00012db70 pc=0x4528a1f
main.STResize(0xc7040a0, 0xc0003a0022)
	/Users/daonb/src/webexec/st.go:25 +0x3f fp=0xc00012dbc0 sp=0xc00012dba0 pc=0x4527fcf
main.(*Pane).Resize(0xc0002b8230, 0xc0000a2a50)
	/Users/daonb/src/webexec/pane.go:172 +0x15c fp=0xc00012dc48 sp=0xc00012dbc0 pc=0x4527afc
main.(*Peer).OnCTRLMsg(0xc000192000, 0xff01, 0xc0004ba000, 0x5b, 0xffff)
	/Users/daonb/src/webexec/peer.go:295 +0x91a fp=0xc00012df00 sp=0xc00012dc48 pc=0x452304a
main.(*Peer).OnCTRLMsg-fm(0x404c101, 0xc0004ba000, 0x5b, 0xffff)
	/Users/daonb/src/webexec/peer.go:267 +0x51 fp=0xc00012df38 sp=0xc00012df00 pc=0x45291e1
github.com/pion/webrtc/v2.(*DataChannel).onMessage(0xc0000fe5a0, 0xc0004ba001, 0xc0004ba000, 0x5b, 0xffff)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:279 +0x7e fp=0xc00012df70 sp=0xc00012df38 pc=0x43b709e
github.com/pion/webrtc/v2.(*DataChannel).readLoop(0xc0000fe5a0)
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:329 +0x4d fp=0xc00012dfd8 sp=0xc00012df70 pc=0x43b741d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00012dfe0 sp=0xc00012dfd8 pc=0x4064ed1
created by github.com/pion/webrtc/v2.(*DataChannel).handleOpen
	/Users/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:294 +0xfd
```

**Comment by daonb** [comment]
Haven't seen this in a week. closing.
