### ISSUE TITLE
C function tputc violates segmentation

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#26]
It's very rare but ti happens:

```
2020-10-27T12:31:21.713+0200    INFO    Setting payload to: "{\"windows\":[{\"name\":\"Tab 1\",\"layout\":{\"dir\":\"topbottom\",\"sx\":1,\"sy\":0.908226469123506,\"xoff\":0,\"yoff\":0,\"cells\":[{\"sx\":0.4699853587115666,\"sy\":0.908226469123506,\"xoff\":0,\"yoff\":0,\"fontSize\":12,\"webexec_id\":1},{\"dir\":\"rightleft\",\"sx\":0.5300146412884333,\"sy\":0.908226469123506,\"xoff\":0.4699853587115666,\"yoff\":0,\"cells\":[{\"sx\":0.5300146412884333,\"sy\":0.908226469123506,\"xoff\":0.4699853587115666,\"yoff\":0,\"fontSize\":12,\"webexec_id\":2,\"active\":true}]}]},\"active\":true},{\"name\":\"Tab 2\",\"layout\":{\"dir\":\"TBD\",\"sx\":1,\"sy\":0.9102769576671511,\"xoff\":0,\"yoff\":0,\"cells\":[{\"sx\":1,\"sy\":0.9102769576671511,\"xoff\":0,\"yoff\":0,\"fontSize\":12,\"webexec_id\":6,\"active\":true}]}}]}"
2020-10-27T12:31:21.713+0200    INFO    Sending ctrl message: {"time":1603794681713,"message_id":16,"type":"ack","args":{"ref":16,"body":{"windows":[{"name":"Tab 1","layout":{"dir":"topbottom","sx":1,"sy":0.908226469123506,"xoff":0,"yoff":0,"cells":[{"sx":0.4699853587115666,"sy":0.908226469123506,"xoff":0,"yoff":0,"fontSize":12,"webexec_id":1},{"dir":"rightleft","sx":0.5300146412884333,"sy":0.908226469123506,"xoff":0.4699853587115666,"yoff":0,"cells":[{"sx":0.5300146412884333,"sy":0.908226469123506,"xoff":0.4699853587115666,"yoff":0,"fontSize":12,"webexec_id":2,"active":true}]}]},"active":true},{"name":"Tab 2","layout":{"dir":"TBD","sx":1,"sy":0.9102769576671511,"xoff":0,"yoff":0,"cells":[{"sx":1,"sy":0.9102769576671511,"xoff":0,"yoff":0,"fontSize":12,"webexec_id":6,"active":true}]}}]}}}
2020-10-27T12:31:22.375+0200    INFO    Sending output to 20 dcs
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.381+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.382+0200    INFO    pane #2: Data channel closed
2020-10-27T12:31:22.490+0200    INFO    Got a CTRLMessage: "{\"type\":\"resize\",\"args\":{\"pane_id\":1,\"sx\":320,\"sy\":64},\"message_id\":11,\"time\":1603794682463}"

2020-10-27T12:31:22.490+0200    INFO    Changing pty size for pane 1: &{64 320 0 0}
2020-10-27T12:31:22.490+0200    INFO    Sending output to 20 dcs
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d pc=0x92cd23]

runtime stack:
runtime.throw(0xa7820e, 0x2a)
        /home/daonb/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /home/daonb/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 77 [syscall]:
runtime.cgocall(0x928de0, 0xc0001f6dd8, 0x3)
        /home/daonb/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0001f6da8 sp=0xc0001f6d70 pc=0x405b8b
main._Cfunc_tputc(0x7fd670000b20, 0x7fd60000004a)
        _cgo_gotypes.go:178 +0x41 fp=0xc0001f6dd8 sp=0xc0001f6da8 pc=0x926221
main.STPutc.func1(0x7fd670000b20, 0xc00000004a)
        /home/daonb/src/webexec/st.go:48 +0x55 fp=0xc0001f6e08 sp=0xc0001f6dd8 pc=0x9283c5
main.STPutc(0x7fd670000b20, 0x4a)
        /home/daonb/src/webexec/st.go:48 +0x33 fp=0xc0001f6e28 sp=0xc0001f6e08 pc=0x927dc3
main.STWrite(0x7fd670000b20, 0xc0011e4be0, 0x96)
        /home/daonb/src/webexec/st.go:54 +0x38 fp=0xc0001f6e68 sp=0xc0001f6e28 pc=0x927e18
main.(*Pane).ReadLoop(0xc000346060)
        /home/daonb/src/webexec/pane.go:115 +0x5d4 fp=0xc0001f7fd8 sp=0xc0001f6e68 pc=0x927084
runtime.goexit()
        /home/daonb/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001f7fe0 sp=0xc0001f7fd8 pc=0x465a41
created by main.(*Peer).OnPaneReq
        /home/daonb/src/webexec/peer.go:222 +0x522
```

**Comment by daonb** [comment]
Added mutex protection. Let's hope it solves this.
