### ISSUE TITLE
Panic on opening new pane

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#28]
```
2020-10-27T14:46:50.974+0200    INFO    Got a channel request: peer authenticate: true, channel label "69x106,zsh"
2020-10-27T14:46:50.974+0200    INFO    Parsing window size: "69x106"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f3058021318 pc=0x7f30acc3614d]

runtime stack:
runtime.throw(0xa7820e, 0x2a)
        /home/daonb/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /home/daonb/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 329 [syscall]:
runtime.cgocall(0x928db0, 0xc000050c60, 0x0)
        /home/daonb/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000050c30 sp=0xc000050bf8 pc=0x405b8b
main._Cfunc_tnew(0x450000006a, 0x0)
        _cgo_gotypes.go:164 +0x4e fp=0xc000050c60 sp=0xc000050c30 pc=0x92617e
main.STNew(...)
        /home/daonb/src/webexec/st.go:20
main.NewPane(0xc000178790, 0x1, 0x1, 0xc00029e2d0, 0xc0003fb500, 0x1, 0xc000178780, 0x2)
        /home/daonb/src/webexec/pane.go:49 +0xf3 fp=0xc000050dd8 sp=0xc000050c60 pc=0x9264e3
main.(*Peer).OnPaneReq(0xc0000e8070, 0xc00029e2d0, 0x7442f0)
        /home/daonb/src/webexec/peer.go:219 +0x438 fp=0xc000050f08 sp=0xc000050dd8 pc=0x921ca8
main.(*Peer).OnChannelReq.func1()
        /home/daonb/src/webexec/peer.go:150 +0x3c fp=0xc000050f40 sp=0xc000050f08 pc=0x927f8c
github.com/pion/webrtc/v2.(*DataChannel).onOpen.func1()
        /home/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:235 +0x2f fp=0xc000050f60 sp=0xc000050f40 pc=0x87ef9f
sync.(*Once).doSlow(0xc00029e360, 0xc0000a0dc0)
        /home/daonb/go/src/sync/once.go:66 +0xec fp=0xc000050fb0 sp=0xc000050f60 pc=0x47208c
sync.(*Once).Do(0xc00029e360, 0xc0000a0dc0)
        /home/daonb/go/src/sync/once.go:57 +0x45 fp=0xc000050fd0 sp=0xc000050fb0 pc=0x471f95
runtime.goexit()
        /home/daonb/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000050fd8 sp=0xc000050fd0 pc=0x465a41
created by github.com/pion/webrtc/v2.(*DataChannel).onOpen
        /home/daonb/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/datachannel.go:234 +0xcd
```

**Comment by daonb** [comment]
Haven't seen it in a long while
