### ISSUE TITLE
Panic on new session

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#30]
When running with --debug on a Darwin:

```log
info    New Peer from: eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDQ3MDkwNDczNjk1MzI2Nzc4NzAgMiBJTiBJUDQgMTI3LjAuMC4xXHJcbnM9LVxyXG50PTAgMFxyXG5hPWdyb3VwOkJVTkRMRSAwXHJcbmE9bXNpZC1zZW1hbnRpYzogV01TXHJcbm09YXBwbGljYXRpb24gNjIyMzMgVURQL0RUTFMvU0NUUCB3ZWJydGMtZGF0YWNoYW5uZ
WxcclxuYz1JTiBJUDQgMC4wLjAuMFxyXG5hPWNhbmRpZGF0ZToyMDg3MjAxMjE1IDEgdWRwIDIxMTM5MzcxNTEgNWE4MjE1ODItOTZiZi00MGIyLWFmYmEtNWQ5YWEzZmYyMjZjLmxvY2FsIDYyMjMzIHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9aWNlLXVmcmFnOjVQNmRcclxuYT1pY2UtcHdkOllBUHplMFRHcVFGUG9nZkxJR
Hp3aHFIeVxyXG5hPWljZS1vcHRpb25zOnRyaWNrbGVcclxuYT1maW5nZXJwcmludDpzaGEtMjU2IEVBOkE5OjY0OkVFOkVDOkY0OjdGOjUzOkMxOkQ4OkZCOjQwOjhCOjczOjFBOjQ4OjY4OkFEOjU5OkVCOjVDOjk2OkExOjI4Ojc2OkM5OjkxOkY1Ojk5OkFEOjAyOjhEXHJcbmE9c2V0dXA6YWN0cGFzc1xyXG5hPW1pZDowXHJcbmE9c2N0cC1wb3J0OjUwMDBcc
lxuYT1tYXgtbWVzc2FnZS1zaXplOjI2MjE0NFxyXG4ifQ==
webexec(99968,0x70000a34d000) malloc: Incorrect checksum for freed object 0x2f008600: probably modified after being freed.
Corrupt value: 0xa
webexec(99968,0x70000a34d000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff675fa33a m=3 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff675fa33a
stack: frame={sp:0x70000a34c268, fp:0x0} stack=[0x70000a2cd350,0x70000a34cf50)
000070000a34c168:  00007fff6768d7da  0000000000000000
000070000a34c178:  000070000a34c1c8  000070000a34c1c0
...
goroutine 859 [syscall]:
runtime.cgocall(0x452d630, 0xc000042dc0, 0xc0000ae048)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000042d90 sp=0xc000042d58 pc=0x40056fb
net._C2func_getaddrinfo(0xc000028740, 0x0, 0xc00023a210, 0xc0000ae048, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:98 +0x55 fp=0xc000042dc0 sp=0xc000042d90 pc=0x41e6765
net.cgoLookupIPCNAME.func1(0xc000028740, 0x12, 0x12, 0xc00023a210, 0xc0000ae048, 0x0, 0x1, 0x3)
        /usr/local/go/src/net/cgo_unix.go:161 +0xd2 fp=0xc000042e08 sp=0xc000042dc0 pc=0x41eb502
net.cgoLookupIPCNAME(0x465ea32, 0x4, 0xc000028700, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:161 +0x183 fp=0xc000042f18 sp=0xc000042e08 pc=0x41e7bf3
net.cgoIPLookup(0xc00011be00, 0x465ea32, 0x4, 0xc000028700, 0x11)
        /usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc000042fb8 sp=0xc000042f18 pc=0x41e8327
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000042fc0 sp=0xc000042fb8 pc=0x4064ca1
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:228 +0xc7
```

**Comment by daonb** [comment]
I don't see it anymore. closing.
