### ISSUE TITLE
Another Abort on resize

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#35]
After solving #23 there's another abort on resize. It could be size related.

```
2020-11-20T20:45:51.282+0200	INFO	Sending ctrl message: {"time":1605897951282,"message_id":19,"type":"ack","args":{"ref":19,"body":{"windows":[{"name":"Tab 1","layout":{"dir":"rightleft","sx":1,"sy":0.9404296875,"xoff":0,"yoff":0,"cells":[{"dir":"topbottom","sx":1,"sy":0.1396484375,"xoff":0,"yoff":0,"cells":[{"sx":1,"sy":0.13964843749999983,"xoff":0,"yoff":0,"fontSize":12,"webexec_id":3}]},{"dir":"topbottom","sx":1,"sy":0.80078125,"xoff":0,"yoff":0.1396484375,"cells":[{"dir":"rightleft","sx":0.7380224260958205,"sy":0.8007812500000013,"xoff":0,"yoff":0.1396484375,"cells":[{"sx":0.7380224260958195,"sy":0.646484375,"xoff":0,"yoff":0.1396484375,"fontSize":12,"webexec_id":7},{"sx":0.7380224260958195,"sy":0.15429687500000056,"xoff":0,"yoff":0.7861328125,"fontSize":12,"webexec_id":11,"active":true}]},{"sx":0.2619775739041798,"sy":0.8007812500000013,"xoff":0.7380224260958205,"yoff":0.1396484375,"fontSize":12,"webexec_id":10}]}]},"active":true}]}}}
2020-11-20T20:45:51.779+0200	INFO	Got a CTRLMessage: "{\"type\":\"resize\",\"args\":{\"pane_id\":7,\"sx\":141,\"sy\":62},\"message_id\":20,\"time\":1605897951735}"

2020-11-20T20:45:51.779+0200	INFO	Changing pty size for pane 7: &{62 141 0 0}
SIGABRT: abort
PC=0x7fff727f133a m=8 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff727f133a
stack: frame={sp:0x70000996fb28, fp:0x0} stack=[0x7000098f0350,0x70000996ff50)
000070000996fa28:  00007fff728847da  0000000000000000 
000070000996fa38:  000070000996fa88  000070000996fa80 
000070000996fa48:  0000000004ee3000  0000700009970000 
000070000996fa58:  00007ffeefbff8a7  00007fff72884765 
000070000996fa68:  0000000000000043  000070000996fb50 
000070000996fa78:  00007fff728a0f24  0000003000000018 
000070000996fa88:  000070000996fb60  000070000996faa0 
000070000996fa98:  0000000000000000  0000000000000000 
000070000996faa8:  0000000000000000  00007fff72884765 
000070000996fab8:  0000000004ee304e  0000000000000000 
000070000996fac8:  0000000000000000  00007fff728808b0 
000070000996fad8:  000070000996fb48  0000000004ee2028 
000070000996fae8:  0000000000000043  00007fff98df0ec0 
000070000996faf8:  00007fff98df0930  00007fff72732065 
000070000996fb08:  0000000000000000  000070000996fb50 
000070000996fb18:  00007fff727348ed  0000000000000000 
000070000996fb28: <00007fff728ade60  0000000000000003 
000070000996fb38:  0000000004ee2028  000070000996fb70 
000070000996fb48:  0000000000000000  000070000996fb90 
000070000996fb58:  00007fff72778808  0000000004ee2028 
000070000996fb68:  00007fff727ec399  00007ffffffff9df 
000070000996fb78:  ffffffff04ee2000  0000000004ee2000 
000070000996fb88:  0000000000000003  000070000996fbf0 
000070000996fb98:  00007fff7286e50b  000070000996fbe8 
000070000996fba8:  0000700009970000  000070000996fcb0 
000070000996fbb8:  0000000000000000  00007fff72881875 
000070000996fbc8:  00000000fc1ce958  0000000006025c00 
000070000996fbd8:  0000000000000024  00000000fc1be85a 
000070000996fbe8:  0000000004dfce00  000070000996fcd0 
000070000996fbf8:  00007fff7287fd27  0000000004af08a0 
000070000996fc08:  0000000000000002  0000000004527cb8 <main.(*Pane).Resize+88> 
000070000996fc18:  0000000006025c00  000000000000000a 
runtime: unknown pc 0x7fff727f133a
stack: frame={sp:0x70000996fb28, fp:0x0} stack=[0x7000098f0350,0x70000996ff50)
000070000996fa28:  00007fff728847da  0000000000000000 
000070000996fa38:  000070000996fa88  000070000996fa80 
000070000996fa48:  0000000004ee3000  0000700009970000 
000070000996fa58:  00007ffeefbff8a7  00007fff72884765 
000070000996fa68:  0000000000000043  000070000996fb50 
000070000996fa78:  00007fff728a0f24  0000003000000018 
000070000996fa88:  000070000996fb60  000070000996faa0 
000070000996fa98:  0000000000000000  0000000000000000 
000070000996faa8:  0000000000000000  00007fff72884765 
000070000996fab8:  0000000004ee304e  0000000000000000 
000070000996fac8:  0000000000000000  00007fff728808b0 
000070000996fad8:  000070000996fb48  0000000004ee2028 
000070000996fae8:  0000000000000043  00007fff98df0ec0 
000070000996faf8:  00007fff98df0930  00007fff72732065 
000070000996fb08:  0000000000000000  000070000996fb50 
000070000996fb18:  00007fff727348ed  0000000000000000 
000070000996fb28: <00007fff728ade60  0000000000000003 
000070000996fb38:  0000000004ee2028  000070000996fb70 
000070000996fb48:  0000000000000000  000070000996fb90 
000070000996fb58:  00007fff72778808  0000000004ee2028 
000070000996fb68:  00007fff727ec399  00007ffffffff9df 
000070000996fb78:  ffffffff04ee2000  0000000004ee2000 
000070000996fb88:  0000000000000003  000070000996fbf0 
000070000996fb98:  00007fff7286e50b  000070000996fbe8 
000070000996fba8:  0000700009970000  000070000996fcb0 
000070000996fbb8:  0000000000000000  00007fff72881875 
000070000996fbc8:  00000000fc1ce958  0000000006025c00 
000070000996fbd8:  0000000000000024  00000000fc1be85a 
000070000996fbe8:  0000000004dfce00  000070000996fcd0 
000070000996fbf8:  00007fff7287fd27  0000000004af08a0 
000070000996fc08:  0000000000000002  0000000004527cb8 <main.(*Pane).Resize+88> 
000070000996fc18:  0000000006025c00  000000000000000a 

goroutine 13974 [syscall]:
runtime.cgocall(0x4529790, 0xc000871b68, 0xc00048fce0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000871b38 sp=0xc000871b00 pc=0x4005beb
main._Cfunc_tresize(0x4f1c450, 0x3e0000008d)
	_cgo_gotypes.go:190 +0x45 fp=0xc000871b68 sp=0xc000871b38 pc=0x4526965
main.STResize.func1(0x4f1c450, 0x3e008d)
	/Users/daonb/src/webexec/st.go:25 +0x5f fp=0xc000871b98 sp=0xc000871b68 pc=0x4528b3f
main.STResize(0x4f1c450, 0xc0003e008d)
	/Users/daonb/src/webexec/st.go:25 +0x3f fp=0xc000871bb8 sp=0xc000871b98 pc=0x45282cf
main.(*Pane).Resize(0xc000192150, 0xc00048fce0)
	/Users/daonb/src/webexec/pane.go:175 +0x190 fp=0xc000871c48 sp=0xc000871bb8 pc=0x4527df0
main.(*Peer).OnCTRLMsg(0xc000193180, 0xff01, 0xc000766000, 0x5c, 0xffff)
	/Users/daonb/src/webexec/peer.go:295 +0x91a fp=0xc000871f00 sp=0xc000871c48 pc=0x452330a
main.(*Peer).OnCTRLMsg-fm(0x404c301, 0xc000766000, 0x5c, 0xffff)
	/Users/daonb/src/webexec/peer.go:267 +0x51 fp=0xc000871f38 sp=0xc000871f00 pc=0x4529301
...
```

**Comment by daonb** [comment]
Haven't seen this again probably fixed when added mutex protection on write
